version: "3.3"

services:
  employees_api:
    build:
      context: .
    volumes:
      - $PWD:/go/src/github.com/coreywkruger/employees
    ports:
      - "3000:3000"
    command: make
    working_dir: /go/src/github.com/coreywkruger/employees
    depends_on:
      - empolyees_db
  empolyees_db:
    image: mysql:latest
    volumes:
      - $PWD/seed:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    env_file:
      - .env
    ports:
      - "5432:5432"