version: "3.3"

services:
  api:
    build:
      context: ./api
    volumes:
      - $PWD/api:/usr/src/app
    ports:
      - "5000:5000"
    command: python api.py
    environment:
      - MYSQL_DATABASE=employees
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
  app:
    build:
      context: ./app
    volumes:
      - $PWD/app:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=5000
  db:
    image: mysql:5.7
    volumes:
      - $PWD/seed:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3306:3306"
