version: "3.3"

services:
  api:
    build:
      context: .
    volumes:
      - $PWD:/usr/src/app
    ports:
      - "5000:5000"
    command: python api.py
    environment:
      - MYSQL_DATABASE=employees
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
  db:
    image: mysql:5.7
    volumes:
      - $PWD/seed:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3306:3306"
