version: "3.3"

services:
  api:
    build:
      context: .
    volumes:
      - $PWD:/go/src/github.com/coreywkruger/employees
    ports:
      - "3000:3000"
    command: make
    working_dir: /go/src/github.com/coreywkruger/employees
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - $PWD/seed:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3306:3306"
