version: "3.3"

services:
  testapi:
    build:
      context: ./api
    volumes:
      - $PWD/api:/usr/src/app
    command: pytest
    environment:
      - MYSQL_DATABASE=test_employees
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - testdb
  testdb:
    image: mysql:5.7
    volumes:
      - $PWD/seed:/docker-entrypoint-initdb.d
      - $PWD/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testemployees
    ports:
      - "3306:3306"
      